const products = [
  {
    id: 1,
    subject: 'Arabic Language Course',
    price: 400,
    quantity: 6,
    image: 'img/arabic.jpg',
    cartquantity: 0,
  },
  {
    id: 2,
    subject: 'English Language Course',
    price: 400,
    quantity: 4,
    image: 'img/english.png',
    cartquantity: 0,
  },
  {
    id: 3,
    subject: 'Biology',
    price: 550,
    quantity: 8,
    image: 'img/biology.jpg',
    cartquantity: 0,
  },
  {
    id: 4,
    subject: 'History',
    price: 300,
    quantity: 6,
    image: 'img/history.jpg',
    cartquantity: 0,
  },
  {
    id: 5,
    subject: 'Law',
    price: 350,
    quantity: 5,
    image: 'img/law1.jpg',
    cartquantity: 0,
  },
  {
    id: 6,
    subject: 'Criminal Law',
    price: 450,
    quantity: 7,
    image: 'img/law2.jpg',
    cartquantity: 0,
  },
  {
    id: 7,
    subject: 'Chemistry',
    price: 550,
    quantity: 7,
    image: 'img/chemistry.jpg',
    cartquantity: 0,
  },
  {
    id: 8,
    subject: 'Artificial Intelligence',
    price: 650,
    quantity: 6,
    image: 'img/artificial_Intelligence.jpg',
    cartquantity: 0,
  },
  {
    id: 9,
    subject: 'Introduction to Robotics',
    price: 700,
    quantity: 9,
    image: 'img/robotics.jpg',
    cartquantity: 0,
  },
  {
    id: 10,
    subject: 'Physics',
    price: 150,
    quantity: 6,
    image: 'img/physics.jpg',
    cartquantity: 0,
  },
];